### ISSUE TITLE
"You don't have a value for screens.sm in your tailwind theme"

### ISSUE THREAD

**Issue by frontedbe** [matiasngf/tailwindcss-text-scale#1]
Hi!

Was trying out your plugin just now as it looks promising!

Unfortunately I get the following error message "You don't have a value for screens.sm in your tailwind theme", but I do have (custom) screens defined under which the 'sm' screen.

Any idea what I'm doing wrong? Thx!

![screenshot](https://github.com/matiasngf/tailwindcss-text-scale/assets/1449125/a491d5b5-be31-45ce-8bee-f6131a24d6b7)

**Comment by matiasngf** [comment]
Hm, that's weird, I'll check it today

**Comment by matiasngf** [comment]
Hi! It's fixed now.
